### PR TITLE
Add additional check when loading tests to only load tests from the file to be tested.

### LINKED ISSUE #128: Doctests from imported functions are also run (when running `python3 ok`)
The culprit seems to be `sources/doctests/__init__._load_tests`. It should probably check that `name` is defined in `module`.

### PR DESCRIPTION
**Pull request by brianhou**
Resolves #128, but could use more testing.

### CODE REVIEW

**Comment by albert12132** [comment]
Looks okay to me, but I'd prefer to have some tests. Also, you'll have to fix some of the existing tests, since they're breaking.

**Comment by brianhou** [comment]
Will do!

**Comment by brianhou** [comment]
Finally added some tests. @albert12132 can you look them over?

**Comment by albert12132** [comment]
LGTM.

**Pull request merged**
