### PR TITLE
Fix sqlite parsing bug

### PR DESCRIPTION
**Pull request by albert12132**

### CODE REVIEW

**Comment by soumyabasu** [comment]
What was the parsing bug?

**Comment by albert12132** [comment]
If a blank line was present in the middle of a sql statement, then the parser would stop at the blank line and not read the rest of the sql statement. For example:

```
create table distance as

    select 'blah';
```

The parser would stop at the blank line right before the "select" and try to execute that. The solution is just to use the built-in `executemany` method in the sqlite3 library.

**Comment by soumyabasu** [comment]
Oh, okay. So instead of you trying to figure out what are SQL statements, you have sqlite do it?

**Comment by albert12132** [comment]
Correct. Instead of OK manually parsing SQLite files, we just run it through the sqlite3 library method.

**Comment by soumyabasu** [comment]
Okay. LGTM. Merging now.

**Pull request merged**
