### PR TITLE
Answer evaluation in UnlockProtocol

### PR DESCRIPTION
**Pull request by jathak**
This implements @papajohn's proposal in #59.

### CODE REVIEW

**Comment by albert12132** [comment]
The way unlocking works is the following:

1. Verify if the student's guess is correct (this is the part you modified).
2. If it is deemed correct, we take the student input (literally just the string they input) to be the answer for the test case.
3. When GradingProtocol runs, it will check if the `repr` of the prompt expression (`>>> x + 4`) is equal to the unlocked answer (again, literally just the string they input).

Suppose we have a prompt:
```
>>> x
?
```
If a student enters `2 + 3` and this is deemed correct, the unlocked test case will look like
```
>>> x
2 + 3
```
Then `GradingProtocol` will check if `repr(x)` (which is the string '5') is equal to the string '2 + 3', which it isn't.

Getting around this requires either rewriting interact or rewriting `GradingProtocol`; changing `_verify` won't be enough.

**Comment by jathak** [comment]
Okay. I get it now. I rewrote this to leave `_verify` as-is, but change `interact` to call `_verify` again with evaluated input if exact string matching fails. If evaluated input matches, it then uses that as the answer for the test case.

**Comment by albert12132** [comment]
The code looks good to me. Can you write one or two tests for this in `tests/protocols/unlock_test.py`?

**Comment by jathak** [comment]
Done.

**Comment by albert12132** [comment]
LGTM.

**Pull request merged**
