### PR TITLE
Always load all protocols

### PR DESCRIPTION
**Pull request by knrafto**
From now on we'll ignore the list of protocols in `protocols`.

### CODE REVIEW

**Comment by choreff** [comment]
Does this mean that we won't need to add `scoring` to the OK files when adding them to the autograder? And that students would be able to run `python3 ok --score`?

**Comment by knrafto** [comment]
Yes to both. Is there a danger to letting students run `python3 ok --score`?

**Comment by choreff** [comment]
I don't think so. I was just clarifying my own understanding.

**Comment by Sumukh** [comment]
The only protocol I'm concerned about is Backup. It's perfectly valid for someone not want to use the backup protocol (data8 did this all last year) and with this PR there is no way to do so (without having the user add arguments every time).  

No other protocol prompts for authentication with a user flag specifying that they want to run that protocol. 

There are a few solutions: 
- A blank endpoint (`""`) prevents backup from running. 
- An optional argument in the `.ok` file that disables the backup protocol.

**Comment by Sumukh** [comment]
Any particular reason you closed this PR?

**Comment by knrafto** [comment]
Hmm how about omitting the endpoint entirely?

**Comment by Sumukh** [comment]
We use the endpoint all over the place - in collab & hinting for example.

If we can get a default value in there - so that using `assignment.endpoint` won't result in attribute error - then that's fine with me.

**Comment by knrafto** [comment]
The endpoint now defaults to the empty string if omitted. If the endpoint is falsey, we won't attempt to backup. I tested the other protocols too manually, and nothing seemed to break.

**Pull request merged**
