### PR TITLE
Temporary Fix for #93

### PR DESCRIPTION
**Pull request by alvinwan**
In case it's needed

### CODE REVIEW

**Comment by Sumukh** [comment]
@albert12132 can weigh in better on this.

This probably isn't the best solution because we'll end up storing an invalid access token. One approach we can try instead is a simply putting this in a try/except block and print an error message.

**Comment by alvinwan** [comment]
That's fair - just let me know if you want the fix.

**Comment by soumyabasu** [comment]
Thinking about this issue a little more- I think we should have a try/except block. If they don't get an authentication token, we should tell students to try again in a couple of minutes and if it still fails, to get in touch with staff/ok-support.

**Comment by papajohn** [comment]
@soumyabasu I'm not too familiar with this issue. I'll let you and @alvinwan decide what's best.

**Comment by Sumukh** [comment]
Closing for now - though having better error messages for students is still an open problem.

**Pull request closed without merging**
