### PR TITLE
Collect rationale for some wrong answers too

### PR DESCRIPTION
**Pull request by Sumukh**
Collect answers outside of the watchlist too.

### CODE REVIEW

**Comment by knrafto** [comment]
Is this for the same study that the prompts were originally for, or a different study?

Do you know some numbers on how often students answer vs Ctrl-Cing or typing gibberish?

**Comment by Sumukh** [comment]
I think it's for the same study - @ksteph might have those stats.

**Comment by ksteph** [comment]
This is for the same study. I don't have the numbers yet on the response rate, but I have asked for them. Hopefully, I'll know by Monday, but it is also spring break :-/

**Comment by Sumukh** [comment]
I'm going to merge this for Lab 10.

**Pull request merged**
