### PR TITLE
Fix bug with reloading tests via API.

### LINKED ISSUE #150: API error when loading an assignment twice
Loading an assignment using the new client API works great the first time. If I execute `load_assignment('lab01.ok')` a second time, then I get the following traceback.

Tests are ok files are all here: https://github.com/data-8/data8assets/tree/gh-pages/labs/lab01

```
---------------------------------------------------------------------------
SerializeException                        Traceback (most recent call last)
/opt/conda/lib/python3.4/site-packages/client/sources/ok_test/__init__.py in load(file, parameter, assign)
     46                                     assign.cmd_args.interactive,
---> 47                                     assign.cmd_args.timeout, **test)}
     48     except ex.SerializeException:

/opt/conda/lib/python3.4/site-packages/client/sources/common/core.py in __call__(cls, *args, **kargs)
    186                                 'argument {}'.format(attr))
--> 187         obj.post_instantiation()
    188         return obj

/opt/conda/lib/python3.4/site-packages/client/sources/ok_test/models.py in post_instantiation(self)
     27             if not isinstance(suite, dict):
---> 28                 raise ex.SerializeException('Test cases must be dictionaries')
     29             elif 'type' not in suite:

SerializeException: Test cases must be dictionaries

During handling of the above exception, another exception occurred:

LoadingException                          Traceback (most recent call last)
<ipython-input-21-9569af2e18b6> in <module>()
      1 # Test cell; please do not change!
      2 from client.api.assignment import load_assignment
----> 3 lab01 = load_assignment('lab01.ok')

/opt/conda/lib/python3.4/site-packages/client/api/assignment.py in load_assignment(filepath, cmd_args)
     22     if cmd_args is None:
     23         cmd_args = _MockNamespace()
---> 24     return Assignment(cmd_args, **config)
     25 
     26 def _get_config(config):

/opt/conda/lib/python3.4/site-packages/client/sources/common/core.py in __call__(cls, *args, **kargs)
    185                 raise ex.SerializeException('__init__() missing expected '
    186                                 'argument {}'.format(attr))
--> 187         obj.post_instantiation()
    188         return obj
    189 

/opt/conda/lib/python3.4/site-packages/client/api/assignment.py in post_instantiation(self)
    107     def post_instantiation(self):
    108         self._print_header()
--> 109         self._load_tests()
    110         self._load_protocols()
    111         self.specified_tests = self._resolve_specified_tests(

/opt/conda/lib/python3.4/site-packages/client/api/assignment.py in _load_tests(self)
    131                 if parameter:
    132                     test_name += ':' + parameter
--> 133                 self.test_map.update(module.load(file, parameter, self))
    134                 log.info('Loaded {}'.format(test_name))
    135 

/opt/conda/lib/python3.4/site-packages/client/sources/ok_test/__init__.py in load(file, parameter, assign)
     47                                     assign.cmd_args.timeout, **test)}
     48     except ex.SerializeException:
---> 49         raise ex.LoadingException('Cannot load OK test {}'.format(file))

LoadingException: Cannot load OK test tests/q30.py
```

### PR DESCRIPTION
**Pull request by brianhou**
I think this resolves #150, but I'm still trying to look through the code to make sure that this is an actual fix.

### CODE REVIEW

**Comment by brianhou** [comment]
The underlying issue seems to be that `OkTest.suites` is a class attribute. It looks intentional, but seems a little weird to me?

**Comment by albert12132** [comment]
`self.suites` actually isn't a class variable. `OkTest` is a type of Serializable object (defined in `client/sources/common/core.py`, which is a meta-class. The `suites = core.List()` you see in `OkTest` just declares that the instance attribute `self.suites` must be a list.

I'm also not able to recreate the bug, using our demo tests:

```
>>> from client.api.assignment import load_assignment
>>> x = load_assignment('config.ok')
=====================================================================
Assignment: Homework 1
OK, version v1.5.0
=====================================================================

>>> x.grade('q1')
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 7
    Failed: 0
[ooooooooook] 100.0% passed

{'locked': 0, 'failed': 0, 'passed': 7}
>>> x = load_assignment('config.ok')
=====================================================================
Assignment: Homework 1
OK, version v1.5.0
=====================================================================

>>> x.grade('q1')
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 7
    Failed: 0
[ooooooooook] 100.0% passed

{'locked': 0, 'failed': 0, 'passed': 7}
```

**Comment by brianhou** [comment]
Which demo are you running? I'm running demo/ok_test and get this on master:

```
brian@tank:ok_test(master) $ pwd
/home/brian/coding/cs61a/ok-client/demo/ok_test
brian@tank:ok_test(master) $ python3
Python 3.4.0 (default, Jun 19 2015, 14:20:21) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; sys.path.insert(0, '../..')
>>> from client.api.assignment import load_assignment 
>>> x = load_assignment('config.ok')
=====================================================================
Assignment: Homework 1
OK, version v1.5.0
=====================================================================

>>> x = load_assignment('config.ok')
=====================================================================
Assignment: Homework 1
OK, version v1.5.0
=====================================================================

Traceback (most recent call last):
  File "../../client/sources/ok_test/__init__.py", line 47, in load
    assign.cmd_args.timeout, **test)}
  File "../../client/sources/common/core.py", line 187, in __call__
    obj.post_instantiation()
  File "../../client/sources/ok_test/models.py", line 28, in post_instantiation
    raise ex.SerializeException('Test cases must be dictionaries')
client.exceptions.SerializeException: Test cases must be dictionaries

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../../client/api/assignment.py", line 24, in load_assignment
    return Assignment(cmd_args, **config)
  File "../../client/sources/common/core.py", line 187, in __call__
    obj.post_instantiation()
  File "../../client/api/assignment.py", line 109, in post_instantiation
    self._load_tests()
  File "../../client/api/assignment.py", line 133, in _load_tests
    self.test_map.update(module.load(file, parameter, self))
  File "../../client/sources/ok_test/__init__.py", line 49, in load
    raise ex.LoadingException('Cannot load OK test {}'.format(file))
client.exceptions.LoadingException: Cannot load OK test tests/q1.py
```

**Comment by albert12132** [comment]
I'm also running `demo/ok_test`. Perhaps it's an OS discrepancy?

**Comment by albert12132** [comment]
LGTM.

**Pull request merged**
